zookeeper:
  image: jplock/zookeeper:3.4.6
  ports:
    - "2181:2181"

kafka1:
  image: wurstmeister/kafka:0.8.2.1
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  volumes:
    - /mnt/sda1/kafka:/kafka
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_NUM_PARTITIONS: 3
    KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    KAFKA_DELETE_TOPIC_ENABLE: "true"
    KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1 #simplifies demo, do not use!
    KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 10 #makes demo snappier, do not use!

kafka2:
  image: wurstmeister/kafka:0.8.2.1
  ports:
    - "9093:9092"
  links: 
    - zookeeper:zk
  volumes:
    - /mnt/sda1/kafka:/kafka
  environment:
    KAFKA_BROKER_ID: 2
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
    KAFKA_ADVERTISED_PORT: 9093
    KAFKA_NUM_PARTITIONS: 3
    KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    KAFKA_DELETE_TOPIC_ENABLE: "true"
    KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1 #simplifies demo, do not use!
    KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 10 #makes demo snappier, do not use!

kafka3:
  image: wurstmeister/kafka:0.8.2.1
  ports:
    - "9094:9092"
  links: 
    - zookeeper:zk
  volumes:
    - /mnt/sda1/kafka:/kafka
  environment:
    KAFKA_BROKER_ID: 3
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
    KAFKA_ADVERTISED_PORT: 9094
    KAFKA_NUM_PARTITIONS: 3
    KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    KAFKA_DELETE_TOPIC_ENABLE: "true"
    KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1 #simplifies demo, do not use!
    KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 10 #makes demo snappier, do not use!

schemaregistry:
  image: confluent/schema-registry:latest
  ports:
    - "8081:8081"
  links:
    - zookeeper

postgres:
  # image: confluent/postgres-bw:0.1
  build: ./postgres
  ports:
    - "5432:5432"

bottledwater:
  image: confluent/bottledwater:0.1
  links:
    - postgres
    - kafka1:kafka
    - schemaregistry:schema-registry

# redis
# elasticsearch